create extension if not exists pgcrypto;

-- PROFILES
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default 'User',
  phone text,
  address text,
  latitude double precision,
  longitude double precision,
  role text not null default 'customer' check (role in ('customer','cashier')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.profiles enable row level security;

create or replace function public.current_user_role()
returns text language sql security definer stable set search_path = public
as $$ select role from public.profiles where id = auth.uid() limit 1 $$;
revoke all on function public.current_user_role() from public;
grant execute on function public.current_user_role() to authenticated;

drop policy if exists profiles_self_select on public.profiles;
create policy profiles_self_select on public.profiles for select to authenticated using (id=auth.uid());
drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles for update to authenticated using (id=auth.uid()) with check (id=auth.uid());

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public
as $$ begin
  insert into public.profiles(id,full_name,role) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','User'),'customer') on conflict(id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- CATEGORIES
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);
alter table public.categories enable row level security;
drop policy if exists categories_select on public.categories;
create policy categories_select on public.categories for select to authenticated using(true);

-- MENU
create table public.menu (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id),
  name text not null,
  description text,
  price numeric(12,2) not null check(price>0),
  image_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.menu enable row level security;
drop policy if exists menu_select on public.menu;
create policy menu_select on public.menu for select to authenticated using(true);
drop policy if exists menu_cashier_insert on public.menu;
create policy menu_cashier_insert on public.menu for insert to authenticated with check(public.current_user_role()='cashier');
drop policy if exists menu_cashier_update on public.menu;
create policy menu_cashier_update on public.menu for update to authenticated using(public.current_user_role()='cashier') with check(public.current_user_role()='cashier');

-- ORDERS
create table public.orders (
  id bigint generated by default as identity primary key,
  order_code text not null unique default ('ORD-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,10))),
  customer_id uuid references public.profiles(id) on delete set null,
  cashier_id uuid references public.profiles(id) on delete set null,
  customer_name text,
  customer_phone text,
  address text,
  latitude double precision,
  longitude double precision,
  total numeric(12,2) not null default 0,
  payment_method text not null check(payment_method in ('cash','qris','transfer')),
  payment_status text not null default 'pending' check(payment_status in ('pending','paid','rejected')),
  status text not null default 'pending' check(status in ('pending','confirmed','preparing','ready','completed','cancelled')),
  ordered_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.orders enable row level security;
drop policy if exists orders_customer_select on public.orders;
create policy orders_customer_select on public.orders for select to authenticated using(customer_id=auth.uid());
drop policy if exists orders_customer_insert on public.orders;
create policy orders_customer_insert on public.orders for insert to authenticated with check(customer_id=auth.uid() and status='pending');
drop policy if exists orders_cashier_select on public.orders;
create policy orders_cashier_select on public.orders for select to authenticated using(public.current_user_role()='cashier');
drop policy if exists orders_cashier_update on public.orders;
create policy orders_cashier_update on public.orders for update to authenticated using(public.current_user_role()='cashier') with check(public.current_user_role()='cashier');

-- ORDER ITEMS
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  menu_id bigint not null references public.menu(id),
  quantity integer not null check(quantity>0),
  unit_price numeric(12,2) not null check(unit_price>=0),
  created_at timestamptz not null default now()
);
alter table public.order_items enable row level security;
drop policy if exists order_items_customer_select on public.order_items;
create policy order_items_customer_select on public.order_items for select to authenticated using(exists(select 1 from public.orders o where o.id=order_items.order_id and o.customer_id=auth.uid()));
drop policy if exists order_items_customer_insert on public.order_items;
create policy order_items_customer_insert on public.order_items for insert to authenticated with check(exists(select 1 from public.orders o where o.id=order_items.order_id and o.customer_id=auth.uid()));
drop policy if exists order_items_cashier_select on public.order_items;
create policy order_items_cashier_select on public.order_items for select to authenticated using(public.current_user_role()='cashier');
drop policy if exists order_items_cashier_insert on public.order_items;
create policy order_items_cashier_insert on public.order_items for insert to authenticated with check(public.current_user_role()='cashier');

-- AUDIT
create table public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity text not null,
  entity_id bigint,
  meta jsonb,
  created_at timestamptz not null default now()
);
alter table public.audit_logs enable row level security;
drop policy if exists audit_insert on public.audit_logs;
create policy audit_insert on public.audit_logs for insert to authenticated with check(actor_id=auth.uid());

-- TOTAL
create or replace function public.recalc_order_total(p_order_id bigint)
returns numeric language plpgsql security invoker set search_path=public
as $$ declare v_total numeric(12,2); begin
  select coalesce(sum(quantity*unit_price),0) into v_total from public.order_items where order_id=p_order_id;
  update public.orders set total=v_total,updated_at=now() where id=p_order_id;
  return v_total;
end $$;
grant execute on function public.recalc_order_total(bigint) to authenticated;

-- SEED
insert into public.categories(name) values('Ayam Geprek'),('Minuman'),('Tambahan') on conflict(name) do nothing;

-- STORAGE
insert into storage.buckets(id,name,public) values('menu-images','menu-images',true) on conflict(id) do update set public=true;
drop policy if exists menu_images_public_read on storage.objects;
create policy menu_images_public_read on storage.objects for select to public using(bucket_id='menu-images');
drop policy if exists menu_images_cashier_insert on storage.objects;
create policy menu_images_cashier_insert on storage.objects for insert to authenticated with check(bucket_id='menu-images' and public.current_user_role()='cashier');
drop policy if exists menu_images_cashier_update on storage.objects;
create policy menu_images_cashier_update on storage.objects for update to authenticated using(bucket_id='menu-images' and public.current_user_role()='cashier') with check(bucket_id='menu-images' and public.current_user_role()='cashier');
drop policy if exists menu_images_cashier_delete on storage.objects;
create policy menu_images_cashier_delete on storage.objects for delete to authenticated using(bucket_id='menu-images' and public.current_user_role()='cashier');

create index if not exists idx_orders_customer_id on public.orders(customer_id);
create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_orders_ordered_at on public.orders(ordered_at desc);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
